# Generated by Django 5.1.9 on 2025-05-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubspottoexcelsheet',
            name='hubspot_object_type',
        ),
        migrations.RemoveField(
            model_name='hubspottoexcelsheet',
            name='hubspot_properties',
        ),
        migrations.AddField(
            model_name='hubspottoexcelsheet',
            name='worksheet_name',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='hubspottoexcelsheet',
            name='file_name',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='hubspottoexcelsheet',
            name='worksheet_position',
            field=models.IntegerField(blank=True),
        ),
    ]
