# Generated by Django 5.1.9 on 2025-05-21 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_customer_features'),
        ('features', '0003_hubspottoexcelsheet_workbook_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledhubspotexport',
            name='hubspottoexcelsheet_ptr',
        ),
        migrations.CreateModel(
            name='CustomerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('workbook_id', models.CharField(blank=True, max_length=280)),
                ('workbook_name', models.CharField(blank=True, max_length=280)),
                ('worksheet_id', models.CharField(blank=True, max_length=280)),
                ('worksheet_position', models.IntegerField(blank=True)),
                ('worksheet_name', models.CharField(blank=True, max_length=280)),
                ('file_name', models.CharField(blank=True, max_length=280)),
                ('file_id', models.CharField(blank=True, max_length=280)),
                ('last_row', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='dashboard.customer')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='features.feature')),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureSetting',
        ),
        migrations.DeleteModel(
            name='ScheduledHubSpotExport',
        ),
    ]
