# Generated by Django 5.1.9 on 2025-05-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_remove_scheduledhubspotexport_hubspottoexcelsheet_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerfeature',
            old_name='last_row',
            new_name='worksheet_last_row',
        ),
        migrations.RemoveField(
            model_name='customerfeature',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='customerfeature',
            name='file_name',
        ),
        migrations.AddField(
            model_name='customerfeature',
            name='worksheet_headers',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfeature',
            name='worksheet_num_columns',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerfeature',
            name='worksheet_num_rows',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
