# Generated by Django 5.1.9 on 2025-05-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_rename_last_row_customerfeature_worksheet_last_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeature',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
