# Generated by Django 5.1.9 on 2025-05-11 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('domain', models.URLField(max_length=180)),
                ('hubspot_portal_id', models.CharField(blank=True, max_length=30)),
                ('_hubspot_secret_app_key', models.CharField(blank=True, db_column='hubspot_secret_app_key', max_length=500)),
                ('_msgraph_site_id', models.CharField(blank=True, db_column='msgraph_site_id', max_length=500)),
                ('_msgraph_drive_id', models.CharField(blank=True, db_column='msgraph_drive_id', max_length=500)),
                ('_msgraph_client_id', models.CharField(blank=True, db_column='msgraph_client_id', max_length=500)),
                ('_msgraph_authority', models.CharField(blank=True, db_column='msgraph_authority', max_length=500)),
                ('_msgraph_scopes', models.CharField(blank=True, db_column='msgraph_scopes', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='dashboard.dashboard')),
            ],
        ),
    ]
