# Generated by Django 5.1.9 on 2025-05-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='_msgraph_tenant_id',
            field=models.CharField(blank=True, db_column='msgraph_tenant_id', max_length=500),
        ),
    ]
