# Generated by Django 5.1.9 on 2025-05-11 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer__msgraph_tenant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='_msgraph_access_token',
            field=models.CharField(blank=True, db_column='msgraph_access_token', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='_msgraph_access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='_msgraph_refresh_token',
            field=models.CharField(blank=True, db_column='msgraph_refresh_token', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='customers', to='dashboard.feature'),
        ),
    ]
