# Generated by Django 5.1.9 on 2025-05-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feature_customer__msgraph_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='_msgraph_client_secret',
            field=models.CharField(blank=True, db_column='msgraph_client_secret', max_length=500),
        ),
    ]
