# Generated by Django 5.1.9 on 2025-05-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customer__msgraph_client_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
