# Generated by Django 5.1.9 on 2025-05-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_feature'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='customers', to='features.feature'),
        ),
    ]
