# Generated by Django 5.1.9 on 2025-05-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_customer_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='_hubspot_client_secret',
            field=models.CharField(blank=True, db_column='hubspot_client_secret', max_length=500),
        ),
    ]
