# Generated by Django 5.1.9 on 2025-05-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customer__hubspot_client_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='features',
        ),
    ]
